### ISSUE TITLE
ParseDouble error when adding new battery model

### ISSUE THREAD

**Issue by anvol** [zscircuits/zs1100a#3]
Existing battery models use dot as delimiter, but it turns out that for adding new models I need to use commas.

Consider replacing comma/dot and setting "CultureInfo.InvariantCulture"

Like this: _Double.Parse("3,5".Replace(',', '.'), CultureInfo.InvariantCulture)_

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at IOTPowerProfiler.BattForm.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by zscircuits** [comment]
Will check this out. 
I think the issue is due to the non US style numbering format set on the PC. 
you may be able to directly edit the battmodel.xml file located in the below folder
C:\Users\username\AppData\Roaming\ZSCircuits\IOTPowerProfiler\Models\Models

Till we fix the issue.
